version: "3.5"
services:
  mongodb:
    container_name: fangstocks-db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbuser
      MONGO_INITDB_ROOT_PASSWORD: dbpass
    ports:
      - "27020:27017"